### ISSUE TITLE
usability things

### ISSUE THREAD

**Issue by hedbergj** [engineerwithoutfear/web_dev#1]
Looks great. I'll just write down what I mentioned in the meeting:
### waves

a) there's more to be gained from adjusting the speed &omega;  and radius _r_ of the wheel, rather than if there are dots or not. Maybe two sliders that let the user change those params. 

b) if you want to turn the waves off, I would make them independent. Maybe two check boxes (can we have those?) : one for the sine wave projection and one for the cosine wave projection

c) and also, we should all conform to accepted conventions: CCW is positive. 

d) Maybe a start/stop button so we can pause the animation?
### averages

a) I think flipping it all vertically will make more sense. People are used to seeing bar graphs go up, rather than down.

**Comment by engineerwithoutfear** [comment]
Thank you for writing this out! I took notes during the meeting so I incorporated most of these since then despite not seeing this until now. (I think I have the email notifications set up properly now, so I should see any more "issues" that issue forth in the future much more quickly.) The pause button is a good idea I hadn't thought of (and somehow didn't make it into my notes), so I may yet add that in...
